In [1]:
import numpy as np

In [3]:
# numpy thu vien toasn hoc ma tran, mang da chieu , toc do xu li nhanh hon
np.array([1, 2, 3,2, 23]) # kieu mang

array([ 1,  2,  3,  2, 23])

In [5]:
np.array([1, 2, 3,2, 23], dtype='float32') # kieu mang chuyen int sang float


array([ 1.,  2.,  3.,  2., 23.], dtype=float32)

In [12]:

a1=np.array([[3, 34, 34,4],
     [4, 54, 65,32]])
a1.shape # kich thuo cot dong

(2, 4)

In [ ]:
# kieu du lieu kich thuoc size

In [15]:
#zeros  tao mag toan so 0
np.zeros([2, 4], dtype= int)  # tao 2 hang va 4 cot

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
# one
np.ones((3, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
# tao mag khoang ty cach tu dau toi dau
np.arange(3, 20, 2) # bat dau tu 3, end 20m, step =2

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
np.full((3, 4), 6.9) # 3 hang 4 cot full 6.9

array([[6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9]])

In [25]:
# tao mang
np.linspace(3, 6, 7)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [26]:
# random
np.random.random((4, 4))

array([[2.96255788e-01, 1.89069488e-04, 3.56719770e-02, 8.31750168e-01],
       [4.25057431e-01, 1.12908462e-01, 9.90374522e-02, 7.88564858e-01],
       [2.48042200e-01, 3.07897855e-01, 7.06982498e-01, 8.76709312e-01],
       [9.63993739e-01, 5.23650138e-01, 4.07607316e-01, 4.34046018e-01]])

In [27]:
np.random.normal(0, 1, (4, 5))

array([[-1.11272022, -0.70487186,  0.13960266, -0.91412153, -1.16461935],
       [-0.4405605 , -0.62989759, -1.16760333,  0.33055968,  0.97009259],
       [ 0.97407379, -2.48272386, -0.36714591,  1.16923339,  2.98009283],
       [ 0.34764066,  1.73468041, -0.50567086, -1.46872363,  0.09751026]])

In [29]:
# random so nguyen ngau nhien
np.random.randint(0, 20, (3, 4))

array([[ 2, 14,  7, 10],
       [ 4, 18,  7,  9],
       [ 5, 11, 16,  3]])

In [32]:
x1=np.random.randint(20, size=6)
print(x1)

[18  7 19 17 12 12]


In [33]:
x1[4] # lay vi tri so 4

12

In [36]:
x2=np.random.randint(10, size=(3, 5))
print(x2)

[[0 8 5 3 8]
 [4 4 3 5 6]
 [7 4 2 8 9]]


In [37]:
x2[1, 2]

3

In [39]:
# update hang 1 cot 2 bang 6
x2[1, 2] =6
print(x2)

[[0 8 5 3 8]
 [4 4 6 5 6]
 [7 4 2 8 9]]


In [40]:
print(x1)

[18  7 19 17 12 12]


In [44]:
print(x1[::3])

[18 17]


In [45]:
print(x2)

[[0 8 5 3 8]
 [4 4 6 5 6]
 [7 4 2 8 9]]


In [46]:
x2[::2, 2]

array([5, 2])

In [50]:
grid= np.arange(1, 10)
grid.shape
print(grid)

[1 2 3 4 5 6 7 8 9]


In [55]:
grid.reshape((3, 3)) # phai la ma tran vuon


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
z=np.array([[4, 5, 6,34],
            [5, 6, 8,2]])
z.T # chuyen cot thanh hang va hang thanh cot

array([[ 4,  5],
       [ 5,  6],
       [ 6,  8],
       [34,  2]])

In [ ]:
# noi casc numpy va casct casc num py thnah cas nho hon

In [61]:
x=np.array([1, 3, 54])
y=np.array([4, 5, 56])

np.concatenate((x, y)) # noi 2 cai mang vao nhau

array([ 1,  3, 54,  4,  5, 56])

In [65]:
mang1 =np.array([[2, 3,45],
                 [4, 5, 6]])
mang1
np.concatenate((mang1, mang1)) # noi mang 2 chieu

array([[ 2,  3, 45],
       [ 4,  5,  6],
       [ 2,  3, 45],
       [ 4,  5,  6]])

In [66]:
x=np.array([2, 4, 5])
y=np.array([[3, 4,5 ],
            [32, 5,5]])
np.vstack((x, y)) # colums colum

array([[ 2,  4,  5],
       [ 3,  4,  5],
       [32,  5,  5]])

In [68]:
#Tach chuo
x=np.array([3, 35, 54,64,46,64])
np.split(x, [3, 5]) # tach ra o casc vi tri

[array([ 3, 35, 54]), array([64, 46]), array([64])]

In [72]:
a= np.arange(7)
print(a)

[0 1 2 3 4 5 6]


In [73]:
print(a+3)

[3 4 5 6 7 8 9]


In [74]:
# sum nupy nhanh hon cua python
np.sum(a)

21

In [77]:
m=np.random.random(10000)
np.sum(m)

5000.197063884672

In [82]:
%timeit sum(m)
%timeit np.sum(m) # sun dungj nhanh hon np

882 µs ± 15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
9.48 µs ± 2.96 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [83]:
np.mean(m) # tim gia tri min

0.5000197063884673

In [84]:
# gia tri max
np.max(m)

0.9999921523264564

In [87]:
# xac xuat thong ke # do lech chuan , phuong sai, variance do phan tan
#standard do phan tan
# mean gia tri trung binh cong het chia count(sodo)
# variance do lech chuan inh phuon
dog_height=[600, 470, 170, 430, 300]
dog_he = np.array(dog_height)
print(dog_he)

[600 470 170 430 300]


In [89]:
np.std(dog_he)

147.32277488562318

In [90]:
# phuong sai
np.var(dog_he)

21704.0

In [91]:
# do lech chuan
np.sqrt(np.var(dog_he))

147.32277488562318

In [94]:
x= np.array([3, 24, 53,32, 24, 42])
np.sort(x)

array([ 3, 24, 24, 32, 42, 53])

In [95]:
# lay laoj index sortnp
np.argsort(x)

array([0, 1, 4, 3, 5, 2])

In [96]:
# mang da chiue
mata = np.random.randint(0, 10, size=(4, 6))

In [97]:
np.sort(mata, axis=0) # 0 bang cot

array([[5, 2, 3, 1, 0, 0],
       [7, 2, 5, 1, 6, 1],
       [8, 3, 7, 3, 6, 2],
       [9, 8, 8, 5, 7, 7]])

In [98]:
np.sort(mata, axis=1) # sap xep hang

array([[2, 2, 3, 5, 6, 7],
       [0, 1, 2, 3, 6, 8],
       [0, 3, 5, 5, 7, 8],
       [1, 1, 7, 7, 8, 9]])

In [104]:
A = np.array([[1, 2,3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[6, 5],
              [4, 3],
              [2, 1]])

[[6 5]
 [4 3]
 [2 1]]


In [105]:
A.dot(B) # hang cot cot hang

array([[20, 14],
       [56, 41],
       [92, 68]])

In [106]:
B.T @ A # b dao chieu tich vo huong voi A

array([[36, 48, 60],
       [24, 33, 42]])

In [108]:
np.random.seed(0) # sinh ra mnga gion nhau
sale= np.random.randint(20, size=(5, 3))
print(sale)

[[12 15  0]
 [ 3  3  7]
 [ 9 19 18]
 [ 4  6 12]
 [ 1  6  7]]


In [112]:
import pandas as pd
weekly= pd.DataFrame(sale, index=["Mon", "Tue", "Wed", "Thus", "Fri"],
                          columns=["sa", "a", "df"])
print(weekly) # co cot va hang

      sa   a  df
Mon   12  15   0
Tue    3   3   7
Wed    9  19  18
Thus   4   6  12
Fri    1   6   7
