In [49]:
import pandas as pd
import numpy as np
import seaborn as sns


In [58]:
data = pd.read_csv('https://raw.githubusercontent.com/hieuu09/Data_Machinelearning/main/train_home.csv', sep=',')
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [56]:
data= pd.read_csv('https://raw.githubusercontent.com/hieuu09/Data_Machinelearning/main/train_home.csv', sep=',', index_col='Id')
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [57]:
data.columns # hien ten cac cot cua no len

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

In [ ]:
# chon ra cac feature dac trung du doan chuan nhat du foan gia nha
#
features=["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]
# lua cho casc trung

In [ ]:
X = data[features]
y = data["SalePrice"]

In [ ]:
Y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid =train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=0)


In [ ]:
X_train.shape # 80 % du lieu
X.shape

(1460, 7)

In [ ]:
# traniing machine learning model
from sklearn.tree import DecisionTreeRegressor
# cau truc cay co cac cai nhanh, re nhanh cac dieu kien cho chinh xasc hon
dt_model = DecisionTreeRegressor(random_state=1)

In [ ]:
dt_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=1)

In [ ]:
y_preds=dt_model.predict(X_valid.head())

In [ ]:
y_preds

array([335000., 140200., 119000., 207500., 112000.])

In [ ]:
pd.DataFrame({'y':y_valid.head(), 'y_preds': y_preds})
# gom 5 phan tu gia tri that y, gia tri ao y_preds du daon gia tri du doanh khac gia tri thuc te la bao nhie

y   y_preds
Id                   
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000  112000.0

In [ ]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model= RandomForestRegressor(random_state=1)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=1)

In [ ]:
rf_val_preds= rf_model.predict(X_valid)
rf_val_preds[:5]

array([271690., 155039., 122024., 188915.,  91147.])

In [ ]:
X_valid.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                    
530    32668       1957      2515         0         3             4   
492     9490       1941       958       620         1             3   
460     7015       1950       979       224         1             3   
280    10005       1977      1156       866         2             4   
656     1680       1971       525       567         1             3   

     TotRmsAbvGrd  
Id                 
530             9  
492             5  
460             5  
280             8  
656             6

In [ ]:
# du doan 1 gia tri duy nhat
rf_model.predict([[6969, 2021,1000, 800, 4, 5, 8]]) #dien tic, nam, tang1 S, tang 2 S, 4 phong tam 5 phong ngu

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([206158.4])